// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBooKZ9Ipk49b_9D-fEM18WnnbRTigbHHU',
    appId: '1:435047922408:web:1740cb06909cdfc65da75d',
    messagingSenderId: '435047922408',
    projectId: 'ppb-project-7eb09',
    authDomain: 'ppb-project-7eb09.firebaseapp.com',
    storageBucket: 'ppb-project-7eb09.appspot.com',
    measurementId: 'G-TL5965PCQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_8g7OMrRRii8eaj0m8xcBE6HRTw9ExRE',
    appId: '1:435047922408:android:1d2fad46042942285da75d',
    messagingSenderId: '435047922408',
    projectId: 'ppb-project-7eb09',
    storageBucket: 'ppb-project-7eb09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkulenhAfJP5FbAge0LHxmau9FLiIOO58',
    appId: '1:435047922408:ios:59329531a55f44125da75d',
    messagingSenderId: '435047922408',
    projectId: 'ppb-project-7eb09',
    storageBucket: 'ppb-project-7eb09.appspot.com',
    iosBundleId: 'com.example.foodExample',
  );
}
